#!/usr/bin/with-contenv bash

# Change permission for all execute files
chmod -R +x /etc/cont-init.d
chmod -R +x /etc/services.d

echo "Application folder belongs to gfly:gfly"

# Both developer and application must be able modify it
chown -Rc gfly:gfly .
find . -type d -exec chmod 775 {} \;
find . -type f -exec chmod ug+rw {} \;

echo "App should be able to write uploaded files to temporary directory"
chown root:gfly /tmp
chmod 775 /tmp
chmod 775 /var/log

# App's permission
chmod -R 775 /home/gfly/app/tmp
chmod -R 775 /home/gfly/app/storage/logs
chmod -R 775 /home/gfly/app/storage/tmp