#!/usr/bin/with-contenv bash

# Change permission for all execute files
chmod -R +x /etc/cont-init.d
chmod -R +x /etc/services.d

echo "Should be able to write uploaded files to temporary directory"
chmod 775 /tmp
chmod 775 /var/log